# file: postgresql/tasks/users_privileges.yml

- name: PostgreSQL | Create replication user
  postgresql_user:
    name: "{{item.name}}"
    db: "{{item.db | default(omit)}}"
    port: "{{postgresql_port}}"
    state: present
    login_host: "{{item.host | default(omit)}}"
    login_user: "{{postgresql_admin_user}}"
    role_attr_flags: "{{item.role_attr_flags | default(omit)}}"
  become: yes
  become_user: "{{postgresql_admin_user}}"
  with_items: "{{postgresql_user_privileges}}"
  when: 
  - postgresql_users | length > 0
  - item.priv is not defined

- name: PostgreSQL | Update the user privileges
  postgresql_privs:
    database: "{{ item.db | default(omit)}}"
    roles: "{{ item.name }}"
    type: database
    privs: "{{ item.priv | default(omit)}}"
    state: present
    port: "{{ postgresql_port }}"
    login_host: "{{ item.host | default(omit) }}"
    login_user: "{{ postgresql_admin_user }}"
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  with_items: "{{ postgresql_user_privileges }}"
  when:
    - item.priv is defined
    - postgresql_users | length > 0
